### ISSUE TITLE
Problem when XPath contains '/' 

### ISSUE THREAD

**Issue by thekid** [1and1/fralax#1]
Have a look at https://github.com/1and1/fralax/blob/master/src/main/java/net/onenandone/fralax/parser/XMLParser.java#L115:
```java
String[] parts = xPathQuery.split("/");
```

This will fail for XPath queries such as `//*[@path= '/']` as far as I see.

**Comment by sfuhrm** [comment]
See also here #3

**Comment by bitionaire** [comment]
We had a rewrite today, so it's not an issue anymore. :+1:
