### ISSUE TITLE
Package Release

### ISSUE THREAD

**Issue by bitionaire** [1and1/fralax#17]
... at [jCenter](https://bintray.com/bintray/jcenter) or [Maven Central](http://search.maven.org/)

Both repositories can be easily included in Gradle. Adding a package to central is harder (more burocracy), but probably wider available. Which repository should we support first?

**Comment by Germandrummer92** [comment]
Maven Central:

- [OSSRH Repo request](https://issues.sonatype.org/browse/OSSRH-21846)
- #19 

Needed to deploy to Maven Central:

1. [Create an maven central account](https://issues.sonatype.org/secure/Signup!default.jspa)
2. [Create gpg key](http://central.sonatype.org/pages/working-with-pgp-signatures.html)
3. [Add Credentials to gradle.properties](http://central.sonatype.org/pages/gradle.html#credentials)
4. [After OSSRH has approved repo, deploy with gradle](http://central.sonatype.org/pages/gradle.html#deployment)

**Comment by Germandrummer92** [comment]
Can you take care of [this](https://issues.sonatype.org/browse/OSSRH-21846?focusedCommentId=354271&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-354271)

**Comment by bitionaire** [comment]
Sure :ok_hand:

**Comment by bitionaire** [comment]
It's [released](http://search.maven.org/#artifactdetails%7Cnet.oneandone%7Cfralax%7C0.1%7Cjar)! 🎉
