### ISSUE TITLE
Problem with result type inference

### ISSUE THREAD

**Issue by sfuhrm** [1and1/fralax#3]
This code

https://github.com/1and1/fralax/blob/master/src/main/java/net/onenandone/fralax/parser/XMLParser.java#L123

determines the result type based on the occurance of simple substring matches.

### Summary

The problem is that the result types (XPathResult subtypes) are not calculated according to the input xpath. The parsing can easily be broken by mistake leading to hard to find bugs. 

### Example At-Matching:

There's the problem that parsing is not that simple. Example for buggy @-Detection:

*Good case*
    //[@attr='foobar']

*Buggy case*
    //[text()='bill@microsoft.com']

Besides that, I think that's not possible to infer the result type like this. 

### Example Single-Type Determination

The parser assumes that when it finds "[" and "=" it must be one result, but this only applies to *unique* attribute values.

*Buggy case*
    //[@firstname='Oliver']

In this case the parser determines the result must be XPathType.ELEMENT, but actually if the attribute values are not unique there can be multiple results (XPathType.MULTIPLE_ELEMENTS).

### Proposal

My proposal is to not try to infer the result code in in the parser, but do parameter typing like in the JPA EntityManager.createQuery:

    <T> TypedQuery<T> createQuery(java.lang.String qlString, java.lang.Class<T> resultClass) 

this would look like this

    <T extends XPathResult> T xpathQuery(java.lang.String xpath, java.lang.Class<T> resultClass) 

An even better solution could be having an appoach with a method per result type:

    XMLElement XMLParser.singleElementOf(String xpath)
    ListOfXMLElements XMLParser.multipleElementsOf(String xpath)
    ...

The latter approach has the big advantage of being statically type safe.

**Comment by bitionaire** [comment]
We had a rewrite today, so it's not an issue anymore. :+1:
